# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('github', 'Github'), ('bitbucket', 'Bitbucket'), ('vk', 'Vkontakte'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('tw', 'Twitter'), ('envelop-o', 'Email')], max_length=20, verbose_name='Социальная сеть')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
    ]
