# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Социальные ссылка', 'verbose_name_plural': 'Социальные ссылки'},
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_network',
            field=models.CharField(choices=[('github', 'Github'), ('bitbucket', 'Bitbucket'), ('vk', 'Vkontakte'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('tw', 'Twitter'), ('envelope-o', 'Email')], max_length=20, verbose_name='Социальная сеть'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=50, verbose_name='URL'),
        ),
    ]
