# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('company_name', models.CharField(max_length=30, verbose_name='Компания')),
                ('text', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
