# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resumeblock_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeblock',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
