# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resumeblock_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeblock',
            options={'ordering': ['display_order'], 'verbose_name': 'Раздел резюме', 'verbose_name_plural': 'Разделы резюме'},
        ),
        migrations.AlterField(
            model_name='chronologicaldata',
            name='from_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='chronologicaldata',
            name='to_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
    ]
