# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='Аватар')),
                ('hello_text', models.TextField(verbose_name='Приветственный текст')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
