# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 23:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20170401_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='proposal_succes_msg',
            field=ckeditor.fields.RichTextField(default=0, verbose_name='Благодарственное письмо'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hello_text',
            field=ckeditor.fields.RichTextField(verbose_name='Приветственный текст'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hello_text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Приветственный текст'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hello_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Приветственный текст'),
        ),
    ]
