# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 23:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20170401_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='proposal_succes_msg_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Благодарственное письмо'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='proposal_succes_msg_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Благодарственное письмо'),
        ),
    ]
